cephadm: remove redundant `ERROR` during check-host
```
ERROR: ERROR: No time synchronization is active
```

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit ace5d41dc580a1ea0d0aba19f07da355b06823ef)